# Generated by Django 6.0.3 on 2026-03-26 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='numbers_markup_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Markup percentage applied on top of SMSPool costs (e.g. 30 = 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
