# Generated by Django 6.0.3 on 2026-03-26 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsettings_numbers_markup_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='usd_to_ngn_rate',
            field=models.DecimalField(decimal_places=2, default=1600.0, help_text='USD to NGN exchange rate used for price conversions', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
