# Generated by Django 6.0.3 on 2026-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformsettings_usd_to_ngn_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='crypto_methods',
            field=models.JSONField(blank=True, default=list, help_text='Crypto payment methods: [{"id":"...","name":"USDT","network":"TRC20","address":"..."}]'),
        ),
    ]
