# Generated by Django 6.0.3 on 2026-04-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_platformsettings_api_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='paystack_public_key',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='paystack_secret_key',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='korapay_encryption_key',
            field=models.CharField(blank=True, default='', help_text='Overrides KORAPAY_ENCRYPTION_KEY in .env', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='korapay_public_key',
            field=models.CharField(blank=True, default='', help_text='Overrides KORAPAY_PUBLIC_KEY in .env', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='korapay_secret_key',
            field=models.CharField(blank=True, default='', help_text='Overrides KORAPAY_SECRET_KEY in .env', max_length=255),
        ),
    ]
