# Generated by Django 6.0.3 on 2026-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoostingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Facebook', 'Facebook')], max_length=20)),
                ('category', models.CharField(choices=[('Followers', 'Followers'), ('Likes', 'Likes'), ('Views', 'Views'), ('Subscribers', 'Subscribers'), ('Comments', 'Comments')], max_length=20)),
                ('price_per_k', models.DecimalField(decimal_places=2, help_text='Price per 1000 units', max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(default=100)),
                ('max_quantity', models.PositiveIntegerField(default=100000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('food_groceries', 'Food & Groceries'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_living', 'Home & Living'), ('health_beauty', 'Health & Beauty')], max_length=30)),
                ('emoji', models.CharField(blank=True, help_text='Emoji for display', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Tailwind gradient classes, e.g. from-violet-500 to-purple-600', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmmPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
