# Generated by Django 6.0.3 on 2026-03-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('Telegram', 'Telegram'), ('YouTube', 'YouTube'), ('Snapchat', 'Snapchat'), ('LinkedIn', 'LinkedIn')], max_length=30)),
                ('service_name', models.CharField(help_text='e.g. Aged Instagram Account, Verified Twitter', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Extra notes for buyer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='WebDevPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to demo video')),
                ('website_url', models.URLField(blank=True, help_text='URL to live demo')),
                ('image_url', models.URLField(blank=True, help_text='Thumbnail/preview image URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, help_text='e.g. E-commerce, Portfolio, Blog', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='delivery_days',
            field=models.PositiveIntegerField(default=3, help_text='Estimated delivery days'),
        ),
        migrations.AddField(
            model_name='gift',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the gift image'),
        ),
        migrations.AddField(
            model_name='gift',
            name='notes',
            field=models.TextField(blank=True, help_text='Extra notes shown to buyer'),
        ),
    ]
