# Generated by Django 6.0.3 on 2026-03-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_socialmediaaccount_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What we paid for this item — used for profit calculation', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What we paid for this account — used for profit calculation', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price (shown to users)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price (shown to users)', max_digits=12),
        ),
    ]
