# Generated by Django 6.0.3 on 2026-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostingservice',
            name='catalog_snapshot_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='boostingservice',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='boostingservice',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='boostingservice',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='boostingservice',
            name='price_per_k',
            field=models.DecimalField(decimal_places=4, help_text='Price per 1000 units', max_digits=12),
        ),
    ]
