# Generated by Django 6.0.3 on 2026-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoostingServiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('cost_per_k_ngn', models.DecimalField(decimal_places=4, max_digits=12)),
                ('min_quantity', models.IntegerField(default=10)),
                ('max_quantity', models.IntegerField(default=10000)),
                ('refill', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boosting Service',
                'verbose_name_plural': 'Boosting Services',
                'ordering': ['platform', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMSCountrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('dial_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Country',
                'verbose_name_plural': 'SMS Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSServiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Service',
                'verbose_name_plural': 'SMS Services',
                'ordering': ['name'],
            },
        ),
    ]
