# Generated by Django 6.0.3 on 2026-03-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('rss', 'RSS SMM Panel'), ('smspool', 'SMSPool'), ('paystack', 'Paystack'), ('other', 'Other')], db_index=True, max_length=30)),
                ('action', models.CharField(help_text='e.g. get_services, place_order, check_status', max_length=100)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Request payload (API keys stripped)')),
                ('response_data', models.JSONField(blank=True, default=dict, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Round-trip time in milliseconds', null=True)),
                ('triggered_by', models.CharField(blank=True, help_text='e.g. celery:sync_boosting_services, user:42, admin:sync', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
