# Generated by Django 6.0.3 on 2026-04-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integrations', '0002_api_call_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
            ],
            options={
                'verbose_name': 'Celery Task Log',
                'verbose_name_plural': 'Celery Task Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_integrations.apicalllog',),
        ),
        migrations.CreateModel(
            name='UserPurchaseLog',
            fields=[
            ],
            options={
                'verbose_name': 'User Purchase Log',
                'verbose_name_plural': 'User Purchase Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_integrations.apicalllog',),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='provider',
            field=models.CharField(choices=[('rss', 'RSS SMM Panel'), ('smspool', 'SMSPool'), ('korapay', 'Korapay'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
