# Generated by Django 6.0.3 on 2026-03-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('social_account', 'Social Media Account'), ('phone_number', 'Phone Number Verification'), ('smm_boost', 'SMM Boosting'), ('website_template', 'Website Template'), ('gift', 'Gift Delivery')], max_length=30),
        ),
    ]
